Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2023-08, with the labels that each got.

#37 [Refactor] #36 Team, Artist의 Event 관계 매핑 수정
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
Labels: 🧬 Back, 🛠 Refactor

#33 [Feature] #29 유저 매핑 연결
  src/main/java/com/happiday/Happi_Day/domain/entity/user/RoleType.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
Labels: ✨ Feature, 🛠 Refactor

#39 [Feature] #38 게시판, 판매글 관련 매핑 마무리
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Comment.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/Board.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/BoardCategory.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/SalesCategory.java
Labels: 🛠 Refactor

#41 [Refactor] #40 이벤트 매핑 리스트 제네릭 수정
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
Labels: 🛠 Refactor

#52 [Feature] #51 User 매핑기준 수정
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
Labels: ✨ Feature, 🛠 Refactor

#53 [Feature] #46 Chat과 User 관계 매핑
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatMessage.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatRoom.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
Labels: 🧬 Back, ✨ Feature

#56 [Feature] #45 팀 기본적인 crud 로직 작성
  src/main/java/com/happiday/Happi_Day/domain/controller/TeamController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamRegisterDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, ✨ Feature

#55 [Feature] #13 아티스트 기본적인 CRUD 로직 작성
  src/main/java/com/happiday/Happi_Day/domain/controller/ArtistController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/ArtistType.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/dto/ArtistRegisterDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/dto/ArtistResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/dto/ArtistUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
Labels: 🧬 Back, ✨ Feature

#58 [Feature] #54 chat 관련 Configuration 추가
  build.gradle
  src/main/java/com/happiday/Happi_Day/config/RedisConfig.java
  src/main/java/com/happiday/Happi_Day/config/WebSocketConfig.java
Labels: 🧬 Back, ✨ Feature

#63 [Feature] #42 아티스트와 관련된 판매글 조회 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/ArtistController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
Labels: 🧬 Back, ✨ Feature

#64 [Feature] #43 아티스트가 속한 팀 조회 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/ArtistController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/TeamController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, ✨ Feature

#65 [Feature] #48 팀에 속한 멤버 조회 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/ArtistController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/TeamController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/dto/ArtistDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/dto/ArtistListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, ✨ Feature

#67 [Hotfix] #66 병합 과정에서 누락된 코드로인한 버그 수정
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, 🐛 Bug

#78 [Feature] #75 팀 이미지 등록 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, 🐛 Bug, ✨ Feature

#80 [Feature] #49 팀이 속한 이벤트 조회 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/TeamController.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, ✨ Feature

#81 [Refactor] #73 팀, 아티스트와 게시글 관계 매핑 수정
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Hashtag.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/BoardCategory.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
Labels: 🧬 Back, 🛠 Refactor

#83 Feat/back/#76 event crud
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
Labels: 🧬 Back, ✨ Feature
