Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2023-09, with the labels that each got.

#88 [Feature] #71 카테고리 생성, 댓글 crud 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/CategoryController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/CommentController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Comment.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/WriteCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/BoardCategory.java
  src/main/java/com/happiday/Happi_Day/domain/repository/CommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/CategoryService.java
  src/main/java/com/happiday/Happi_Day/domain/service/CommentService.java
Labels: 🧬 Back, ✨ Feature

#90 [Feature] #89 Article, Comment user 정보 저장, 글 좋아요 기능 구현
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/CommentController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/CommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/CommentService.java
Labels: 🧬 Back, ✨ Feature

#93 Feat/back/#86 event like join
  src/main/java/com/happiday/Happi_Day/config/WebSecurityConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventCommentController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventComment.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventCommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
Labels: 📬 API, 🧬 Back, ✨ Feature

#94 [Featrue]#91 Sales 판매글 CRUD
  src/main/java/com/happiday/Happi_Day/domain/controller/CategoryController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/dto/CreateArticleCategoryDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Order.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Product.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/CreateProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/CreateSalesCategoryDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/WriteSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ProductRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesCategoryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/CategoryService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
Labels: 🧬 Back, ✨ Feature

#96 [Feature] #95 product(판매 옵션) crud 기능 구현
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/ProductController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Product.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ProductService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor
