Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2023-10, with the labels that each got.

#97 [Project] #92 JaCoCo 설정
  build.gradle
Labels: 🧬 Back, ⚙ Setup

#99 [Feature]#98 판매글(Sales) 찜하기 기능 구현
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
Labels: 🧬 Back, ✨ Feature

#102 [Feature]#101 이벤트 참여하기 기능 구현
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventCommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
Labels: 🧬 Back, ✨ Feature

#105 [Feature] #100 이미지 저장 방식 변경
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
Labels: 🧬 Back

#110 [Feature] #106 토큰 받아오는 기능 수정 & 로그인 후 채팅/게시글 조회 선택 추가
  frontend/src/components/ChatWithUser.vue
  frontend/src/components/CreateChatRoom.vue
  frontend/src/components/Login.vue
  frontend/src/components/MyChatRoom.vue
  frontend/src/components/SelectOption.vue
  frontend/src/router/index.js
  src/main/java/com/happiday/Happi_Day/config/WebSecurityConfig.java
Labels: ✨ Feature, 🎨 Front

#111 [Feature] #103 이벤트 지도 조회 test 추가, 이벤트 글로벌 예외처리
  src/main/java/com/happiday/Happi_Day/config/WebSecurityConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventMapController.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventCommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/resources/templates/map-test.html
Labels: 🧬 Back, 🎨 Front
