Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2023-12, with the labels that each got.

#158 [Refactor] db seeder 예외 처리
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleCommentInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArtistInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/BoardInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/DeliveryInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventCommentInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/OrderInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ProductInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesCategoryInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/TeamInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/UserInitService.java
Labels: 🛠 Refactor

#160 [Feature] #159 굿즈/공구 기타 기능 추가
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Order.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/OrderRequestDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/WriteSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/OrderService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
Labels: 🧬 Back, ✨ Feature

#166 [Feature] 이벤트 조회수 기능 추가 / QueryDSL 수정
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCustomRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCustomRepositoryImpl.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#168 [Feature] 기본 이미지 url 반환 유틸 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArtistInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/TeamInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/UserInitService.java
  src/main/java/com/happiday/Happi_Day/utils/DefaultImageUtils.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#169 [Feature] 조회수 중복 방지 로직 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventMapController.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/domain/service/RedisService.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#170 [Feature] 유저 프로필 이미지 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/UserAuthController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/CustomUserDetails.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/dto/UserResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/service/UserInitService.java
Labels: 🧬 Back, ✨ Feature

#173 [Feature] 이벤트 기타 기능 추가/수정
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCustomRepositoryImpl.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor
