Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2023-11, with the labels that each got.

#113 [Feature] #112 이벤트 기본 이미지 추가, 컬럼 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/utils/FileUtils.java
Labels: 🧬 Back, ✨ Feature

#116 [Feature] #106 채팅 웹소켓 연결 및 프론트
  frontend/src/components/ChatWithUser.vue
  src/main/java/com/happiday/Happi_Day/config/StompHandler.java
  src/main/java/com/happiday/Happi_Day/config/WebConfig.java
  src/main/java/com/happiday/Happi_Day/config/WebSecurityConfig.java
  src/main/java/com/happiday/Happi_Day/config/WebSocketConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/ChatController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/ChatRoomController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/HomeController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatRoom.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatRoomResponse.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatMessageDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatNicknameDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatRoomDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatRoomResponse.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/CustomUserDetails.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ChatMessageRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ChatRoomRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatRedisService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatRoomService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatService.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/main/java/com/happiday/Happi_Day/jwt/JwtTokenFilter.java
  src/main/java/com/happiday/Happi_Day/jwt/JwtTokenUtils.java
  src/main/resources/static/assets/js/user.js
  src/main/resources/templates/chat.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
Labels: 📬 API, 🧬 Back, ✨ Feature, 🎨 Front

#119 [Feature] deletedAt 컬럼 추가
  src/main/java/com/happiday/Happi_Day/domain/entity/BaseEntity.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/utils/FileUtils.java
Labels: 🧬 Back, ✨ Feature

#123 [Project] #121 GitHub Actions를 통한 Jira 이슈 연동 세팅
  .github/workflows/create_jira_issue.yml
Labels: ⚙ Setup

#122 [Refactor] #115 채팅기능 refactor 및 채팅방 삭제 기능 수정
  src/main/java/com/happiday/Happi_Day/domain/controller/ChatRoomController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserAuthController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatRoom.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ChatRoomRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatRoomService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatService.java
  src/main/java/com/happiday/Happi_Day/domain/service/JpaUserDetailsManager.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
Labels: 🧬 Back, 🛠 Refactor

#128 [Refactor] #127 이벤트 SoftDelete 및 Paging 처리
  src/main/java/com/happiday/Happi_Day/domain/controller/EventCommentController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventComment.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventCommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#130 [Docs] PR 템플릿 추가
  .github/pull_request_template.md
Labels: ⚙ Setup

#132 [Refactor] #117 페이지 조회, 예외처리
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/CommentController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/OrderController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/OrderStatus.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/CommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/OrderRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/CommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/OrderService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ProductService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
Labels: 🧬 Back, 🛠 Refactor

#135 [Refactor] Article, Sales soft delete 적용
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleCommentController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/ArticleComment.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/WriteCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/BoardCategory.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Order.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/OrderedProduct.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Product.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleCommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/CommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleCommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
Labels: 🧬 Back, 🛠 Refactor

#140 [Feature] 유저, 어드민 기능 추가
  src/main/java/com/happiday/Happi_Day/config/WebSecurityConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/ArtistController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/TeamController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserAuthController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/CustomUserDetails.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleCommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/OrderRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/JpaUserDetailsManager.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
Labels: 🧬 Back, ✨ Feature

#142 [Feature] 기타 기능 추가/수정 + 코드 수정사항
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleCommentController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/DeliveryController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/OrderController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Delivery.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Order.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Product.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/CreateDeliveryDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/OrderRequestDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadDeliveryDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleCommentRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/DeliveryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/DeliveryService.java
  src/main/java/com/happiday/Happi_Day/domain/service/OrderService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ProductService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#145 [Refactor] 유저 로직 리팩토링
  src/main/java/com/happiday/Happi_Day/config/RedisConfig.java
  src/main/java/com/happiday/Happi_Day/config/RedisRepositoryConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserAuthController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatRoomService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatService.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/main/java/com/happiday/Happi_Day/domain/service/RedisSubscriber.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
Labels: ✨ Feature, 🛠 Refactor

#146 [Feature] 팀/아티스트 조회 시 관련 상품 및 이벤트가 조회되도록 기능 추가
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/dto/ArtistDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: ✨ Feature, 🛠 Refactor

#149 [Project] CommandLineRunner를 활용한 DB Seeder 추가
  src/main/java/com/happiday/Happi_Day/config/PasswordEncoderConfig.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/BoardCategoryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/DeliveryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ProductRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesCategoryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamRepository.java
  src/main/java/com/happiday/Happi_Day/initialization/DataInitManager.java
  src/main/java/com/happiday/Happi_Day/initialization/DbSeeder.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleCommentInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArtistInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/BoardInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ChatInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/DeliveryInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventCommentInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/OrderInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ProductInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesCategoryInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/TeamInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/UserInitService.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor, ⚙ Setup

#150 [Feature] 이벤트 리스트 동적 쿼리 조회 추가
  build.gradle
  src/main/java/com/happiday/Happi_Day/config/QueryDslConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QueryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
Labels: 🧬 Back, ✨ Feature
