Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2023-07, with the labels that each got.

#15 [Feature] #3 ChatEntity 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/ChatMessage.java
  src/main/java/com/happiday/Happi_Day/domain/entity/ChatRoom.java
Labels: ✨ Feature

#10 [Feature] #5 BoardEntity 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/Board.java
  src/main/java/com/happiday/Happi_Day/domain/entity/BoardCategory.java
Labels: ✨ Feature

#14 [Feature] #12 팀, 아티스트 엔티티 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
Labels: 🧬 Back, ✨ Feature

#17 [Refactor] #16 Base Entity 수정
  src/main/java/com/happiday/Happi_Day/domain/entity/BaseEntity.java
Labels: 🧬 Back, 🛠 Refactor

#8 [Feature] #6 EventEntity 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventComment.java
Labels: ✨ Feature

#28 [Feature] #27 UserEntity 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/user/RoleType.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
Labels: ✨ Feature

#23 [Feature] #21 상품 관련 Entity 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/board/Board.java
  src/main/java/com/happiday/Happi_Day/domain/entity/board/BoardCategory.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Order.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/OrderStatus.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Product.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/ProductStatus.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/SalesCategory.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/SalesStatus.java
Labels: ✨ Feature, 🛠 Refactor

#31 [Feature] #26 팀, 아티스트 관련 매핑 연결
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
Labels: 🧬 Back, ✨ Feature
