Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2024-04, with the labels that each got.

#252 [Test] Article Controller 테스트 코드 작성
  src/test/java/com/happiday/Happi_Day/domain/controller/article/ArticleCommentControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/controller/article/ArticleControllerTest.java
Labels: 🧪 Testing

#253 [Test] Event 테스트 코드 작성
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventReviewController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistEventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventHashtagRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamEventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/test/java/com/happiday/Happi_Day/controller/EventControllerTest.java
  src/test/java/com/happiday/Happi_Day/service/EventServiceTest.java
Labels: 🧬 Back, 🎨 Front, 🛠 Refactor, 🧪 Testing

#254 [Release] 일부 테스트 업데이트 0.0.7 (Test)
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventReviewController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistEventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventHashtagRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamEventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/test/java/com/happiday/Happi_Day/controller/EventControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/controller/article/ArticleCommentControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/controller/article/ArticleControllerTest.java
  src/test/java/com/happiday/Happi_Day/service/EventServiceTest.java
Labels: 🧬 Back, 🌏 Deploy

#256 [Test] 판매글 관련 Repository 테스트 코드 작성
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/HashtagRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/OrderRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/OrderedProductRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/ProductRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/QuerySalesRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/SalesHashtagRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/SalesLikeRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/SalesRepositoryTest.java
Labels: 🧪 Testing

#257 [Release] 스프린트 10 종료에 따른 정기 업데이트 0.0.9 (Test)
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/HashtagRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/OrderRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/OrderedProductRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/ProductRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/QuerySalesRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/SalesHashtagRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/SalesLikeRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/sales/SalesRepositoryTest.java
Labels: 🧬 Back, 🌏 Deploy

#258 [Test] 마이페이지 Test
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/review/EventReviewResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleLikeRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/test/java/com/happiday/Happi_Day/HappiDayApplicationTests.java
  src/test/java/com/happiday/Happi_Day/domain/controller/UserControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/MyPageServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/article/ArticleCommentServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/article/ArticleServiceTest.java
  src/test/java/com/happiday/Happi_Day/service/EventServiceTest.java
Labels: 🧪 Testing

#261 [Release] 요구 사항 적용에 따른 일부 코드 수정 0.0.11 (Test)
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListCommentDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/comment/EventCommentListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/review/EventReviewResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleLikeRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/test/java/com/happiday/Happi_Day/HappiDayApplicationTests.java
  src/test/java/com/happiday/Happi_Day/domain/controller/UserControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/MyPageServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/article/ArticleCommentServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/article/ArticleServiceTest.java
  src/test/java/com/happiday/Happi_Day/service/EventServiceTest.java
Labels: 🧬 Back, 🌏 Deploy

#265 [Test] 마이페이지 테스트 수정
  src/main/java/com/happiday/Happi_Day/domain/entity/user/dto/UserUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/test/java/com/happiday/Happi_Day/domain/controller/UserAuthControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/controller/UserControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/MailServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/MyPageServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/TokenServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/UserServiceTest.java
Labels: ✨ Feature, 🛠 Refactor, 🧪 Testing

#267 [Release] 스프린트 11 종료에 따른 정기 업데이트 0.0.12 (Test)
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/dto/UserUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/test/java/com/happiday/Happi_Day/domain/controller/UserAuthControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/controller/UserControllerTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/MailServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/MyPageServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/TokenServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/UserServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/sales/DeliveryServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/sales/OrderServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/sales/ProductServiceTest.java
  src/test/java/com/happiday/Happi_Day/domain/service/sales/SalesServiceTest.java
Labels: 🧬 Back, 🌏 Deploy
