Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2024-03, with the labels that each got.

#233 [Test] 아티스트 repository test 추가
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistArticleRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistCustomRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistEventRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistSalesRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistSubscriptionRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistTeamRepositoryTest.java
Labels: 🧬 Back, 🧪 Testing

#235 [Refactor] DB 시더 데이터 추가
  src/main/java/com/happiday/Happi_Day/initialization/DataInitManager.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArtistInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SubscriptionInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/TeamInitService.java
Labels: 🧬 Back, 🛠 Refactor

#236 [Release] 일부 테스트 코드 및 덤프 데이터 추가에 따른 업데이트 0.0.5 (Test)
  src/main/java/com/happiday/Happi_Day/initialization/DataInitManager.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArtistInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SubscriptionInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/TeamInitService.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistArticleRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistCustomRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistEventRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistSalesRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistSubscriptionRepositoryTest.java
  src/test/java/com/happiday/Happi_Day/domain/repository/artist/ArtistTeamRepositoryTest.java
Labels: 🧬 Back, 🌏 Deploy

#243 [Feature] Sales 관련 기능 수정
  src/main/java/com/happiday/Happi_Day/domain/controller/DeliveryController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/ProductController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Order.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/CreateProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/OrderRequestDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateProductDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/WriteSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/DeliveryRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/DeliveryService.java
  src/main/java/com/happiday/Happi_Day/domain/service/OrderService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ProductService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/OrderInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
Labels: 🧬 Back, ✨ Feature
