Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2024-02, with the labels that each got.

#211 [Refactor] 팀 / 아티스트 관련 조인 테이블을 엔티티로 승격
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/ArtistArticle.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/ArtistEvent.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/ArtistSubscription.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/TeamArticle.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/TeamEvent.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/TeamSubscription.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistEventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistSubscriptionRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCustomRepositoryImpl.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QueryArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QuerySalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamEventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamSubscriptionRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SubscriptionService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventInitService.java
Labels: 🧬 Back, 🛠 Refactor

#218 [Refactor] 구독중인 팀/아티스트 조회 관련 로직 수정
  src/main/java/com/happiday/Happi_Day/domain/repository/EventCustomRepositoryImpl.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QueryArticleRepository.java
Labels: 🧬 Back, 🛠 Refactor

#219 [Refactor] 판매글-팀/아티스트 조인 테이블을 엔티티로 승격
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/Artist.java
  src/main/java/com/happiday/Happi_Day/domain/entity/artist/ArtistSales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesDetailResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/TeamSales.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistSalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QuerySalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamSalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
Labels: 🛠 Refactor

#225 [Refactor] 팀/아티스트 페이지네이션
  src/main/java/com/happiday/Happi_Day/domain/controller/ArtistController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/TeamController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistCustomRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArtistCustomRepositoryImpl.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamCustomRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/TeamCustomRepositoryImpl.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArtistService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, 🛠 Refactor

#227 [Refactor] 팀 등록 시, 아티스트를 선택하여 추가 및 등록할 수 있도록 수정
  src/main/java/com/happiday/Happi_Day/domain/controller/SubscriptionController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/subscription/dto/SubscriptionArtistsDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/subscription/dto/SubscriptionTeamsDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/Team.java
  src/main/java/com/happiday/Happi_Day/domain/entity/team/dto/TeamRegisterDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/SubscriptionService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TeamService.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor
