Repository Happi-Cat-Tiger/Happi-Day-Back, pull requests merged in 2024-01, with the labels that each got.

#176 [Feature] 마이페이지 추가 및 코드 리팩토링
  src/main/java/com/happiday/Happi_Day/config/WebSocketConfig.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/main/java/com/happiday/Happi_Day/domain/service/TokenService.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#178 [Featrue] 굿즈/공구 기타기능 추가, 필터링 기능 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/WriteArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesSearchFilteringDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/UpdateSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/WriteSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QuerySalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
Labels: 🧬 Back, ✨ Feature

#179 [Feat] 이벤트 리뷰 기능 추가 및 이벤트 코드 리팩토링
  src/main/java/com/happiday/Happi_Day/domain/controller/EventCommentController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/EventReviewController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventReview.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/ReviewImage.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/review/EventReviewCreateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/review/EventReviewResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/review/EventReviewUpdateDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventReviewRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ReviewImageRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventReviewService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventInitService.java
  src/main/java/com/happiday/Happi_Day/utils/FileUtils.java
Labels: 🧬 Back, ✨ Feature

#183 [Feature] 기본 이미지 주소 반환 엔드포인트 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/DefaultImagesController.java
  src/main/java/com/happiday/Happi_Day/utils/defaultImageDto/DefaultImageUrlResponseDto.java
Labels: 🧬 Back, ✨ Feature

#184 [Feature] 게시글, 판매글 조회수 기능 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
Labels: 🧬 Back, ✨ Feature

#186 [Feature] 채팅 기능 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/ChatRoomController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatMessage.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/ChatRoom.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatMessageDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatRoomDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/chat/dto/ChatRoomResponse.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ChatMessageRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/UserRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ChatService.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/resources/static/assets/js/user.js
  src/main/resources/templates/chat.html
Labels: 📬 API, 🧬 Back, ✨ Feature, 🛠 Refactor

#189 [Refactor] 이벤트 기타 기능 추가/수정
  src/main/java/com/happiday/Happi_Day/domain/controller/EventReviewController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/UserController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/review/EventReviewListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventReviewRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventCommentService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventReviewService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
  src/main/java/com/happiday/Happi_Day/initialization/DataInitManager.java
  src/main/java/com/happiday/Happi_Day/initialization/service/EventReviewInitService.java
  src/main/java/com/happiday/Happi_Day/utils/HashtagUtils.java
Labels: 🧬 Back, ✨ Feature, 🛠 Refactor

#196 [Hotfix] : response 무한 루프 관련 핫픽스
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/SalesListResponseDto.java
Labels: 🧬 Back, 🐛 Bug

#197 [Docs] README 업데이트
  README.md
  docs/architecture.png
  docs/flow-chart-ver1.png
  docs/profile/김도영.jpg
  docs/profile/김소영.jpg
  docs/profile/이용준.jpg
  docs/profile/최수민.jpg
Labels: 📃 Docs

#198 [Feature] 유효성 검사 추가
  src/main/java/com/happiday/Happi_Day/domain/controller/UserAuthController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/dto/UserRegisterDto.java
  src/main/java/com/happiday/Happi_Day/domain/service/JpaUserDetailsManager.java
  src/main/java/com/happiday/Happi_Day/domain/service/UserService.java
  src/main/java/com/happiday/Happi_Day/exception/ErrorCode.java
Labels: 🧬 Back, ✨ Feature

#201 [Refactor] 이벤트 관련 조인 테이블 엔티티 승격
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Hashtag.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/Event.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventHashtag.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventLike.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/EventParticipation.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventListResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/event/dto/EventResponseDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventHashtagRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventLikeRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventParticipationRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/EventRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventReviewService.java
  src/main/java/com/happiday/Happi_Day/domain/service/EventService.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/main/java/com/happiday/Happi_Day/utils/HashtagUtils.java
Labels: 🧬 Back, 🛠 Refactor

#202 [Refactor][Feature] 엔티티승격, 기타기능 수정
  src/main/java/com/happiday/Happi_Day/domain/controller/ArticleController.java
  src/main/java/com/happiday/Happi_Day/domain/controller/SalesController.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Article.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/ArticleHashtag.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/ArticleLike.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/Hashtag.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadListArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/article/dto/ReadOneArticleDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/Sales.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/SalesHashtag.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/SalesLike.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadListSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneOrderDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/product/dto/ReadOneSalesDto.java
  src/main/java/com/happiday/Happi_Day/domain/entity/user/User.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleHashtagRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleLikeRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/ArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QueryArticleRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/QuerySalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesHashtagRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesLikeRepository.java
  src/main/java/com/happiday/Happi_Day/domain/repository/SalesRepository.java
  src/main/java/com/happiday/Happi_Day/domain/service/ArticleService.java
  src/main/java/com/happiday/Happi_Day/domain/service/MyPageService.java
  src/main/java/com/happiday/Happi_Day/domain/service/OrderService.java
  src/main/java/com/happiday/Happi_Day/domain/service/SalesService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/ArticleInitService.java
  src/main/java/com/happiday/Happi_Day/initialization/service/SalesInitService.java
Labels: 🧬 Back, ✨ Feature

#205 [Refactor] CORS 설정 프론트엔드 URL 설정
  src/main/java/com/happiday/Happi_Day/config/CommonConfig.java
  src/main/java/com/happiday/Happi_Day/config/WebSecurityConfig.java
Labels: 🧬 Back, 🛠 Refactor

#207 [Test] 유저 테스트
  .gitignore
  build.gradle
  src/main/java/com/happiday/Happi_Day/config/MailConfig.java
  src/main/java/com/happiday/Happi_Day/domain/service/MailService.java
  src/test/java/com/happiday/Happi_Day/domain/entity/user/UserTest.java
Labels: 🧪 Testing
